name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Install dependencies
        run: dotnet restore
        working-directory: Full-Text-Search-C#
      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: Full-Text-Search-C#
      - name: Test
        run: dotnet test --no-restore --verbosity normal --collect:"XPlat Code Coverage"
        working-directory: Full-Text-Search-C#/Full-Text-Search-C#.Test
       - name: Publish code coverage reports to codecove.io
         uses: codecov/codecov-action@v1
         with:
           token: 9da38875-9455-4708-9a94-e67060befdc0
           files: ./**/coverage.cobertura.xml
           fail_ci_if_error: true